<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net9.0</TargetFrameworks>
    <AssemblyName>namasdev.Data.en</AssemblyName>
    <RootNamespace>namasdev.Data.en</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <PackageId>namasdev.Data.en</PackageId>
    <Version>2.0.0</Version>
    <Authors>Matias Alberto Lopez</Authors>
    <Description>namasdev Data library (English)</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>2024</Copyright>
    <PackageTags>namasdev</PackageTags>
    <AssemblyVersion>2.0.0</AssemblyVersion>
    <FileVersion>2.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="namasdev.Core.en" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <Reference Include="System.Transactions" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

</Project>
